# -*- coding: utf-8 -*-
"""motor_recomendacion_visual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuwfS_R3e_f8b2ykHH21ig12yFI04rGF

# Motor de Recomendación Visual — Prototipo en Colab

**Objetivo:** Validar el pipeline completo CLIP → pgvector con imágenes reales del inventario antes de construir el servicio de producción.

**Modelos usados:**
- `openai/clip-vit-base-patch32` → encoder de imagen (inventario + cliente)
- `sentence-transformers/clip-ViT-B-32-multilingual-v1` → encoder de texto en español (cliente)

**Importante:** Ejecutar las secciones en orden. Cada sección depende de la anterior.

---
## Instrucciones de entorno
1. Ir a **Entorno de ejecución → Cambiar tipo de entorno de ejecución**
2. Seleccionar **GPU T4**
3. Ejecutar desde la Sección 1 en orden

---
## Sección 1: Instalación de dependencias

Solo se ejecuta una vez por sesión de Colab.
"""

# ==============================================================================
# SECCIÓN 1 — Instalación de dependencias
# ==============================================================================
# torch y transformers: framework de deep learning y acceso a los modelos CLIP
# sentence-transformers: modelo multilingüe para texto en español
# Pillow: carga y transformación de imágenes
# numpy: operaciones vectoriales (normalización L2)
# pgvector: tipo de dato vectorial para PostgreSQL
# psycopg2-binary: driver de conexión a PostgreSQL
# ==============================================================================

!pip install -q \
    torch torchvision \
    transformers \
    sentence-transformers \
    Pillow \
    numpy \
    pgvector \
    psycopg2-binary

print("✅ Dependencias instaladas")

"""---
## Sección 2: Verificación del entorno GPU

Confirma que Colab asignó una GPU T4. Si no hay GPU disponible, el notebook funciona igual pero más lento.
"""

# ==============================================================================
# SECCIÓN 2 — Verificación del entorno
# ==============================================================================

import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Dispositivo activo : {DEVICE}")

if DEVICE == "cuda":
    print(f"GPU detectada      : {torch.cuda.get_device_name(0)}")
    print(f"Memoria GPU total  : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("⚠️  Sin GPU. El notebook funcionará en CPU (más lento).")
    print("   Ir a Entorno de ejecución → Cambiar tipo de entorno → GPU T4")

"""---
## Sección 3: Carga de imágenes del inventario

Sube tus imágenes de artículos directamente a Colab. El proceso es:
1. Ejecuta la celda de abajo
2. Aparecerá un botón **Seleccionar archivos**
3. Selecciona todas tus imágenes de artículos (JPEG o PNG)
4. Espera a que terminen de subir

**Formato esperado del nombre de archivo:** cualquier nombre es válido para el prototipo. El sistema usará el nombre del archivo como identificador temporal del artículo.

**Ejemplo:** `silla_tiffany_dorada.jpg`, `mesa_rustica_180.jpg`, etc.
"""

# ==============================================================================
# SECCIÓN 3 — Carga de imágenes del inventario
# ==============================================================================

from google.colab import files
from pathlib import Path
from PIL import Image
import io

EXTENSIONES_VALIDAS = {".jpg", ".jpeg", ".png", ".webp"}
DIRECTORIO_INVENTARIO = Path("/content/inventario")
DIRECTORIO_INVENTARIO.mkdir(exist_ok=True)

print("Selecciona las imágenes de tus artículos...")
archivos_subidos = files.upload()

# Validar y guardar cada imagen
imagenes_validas = []
errores = []

for nombre_archivo, contenido in archivos_subidos.items():
    extension = Path(nombre_archivo).suffix.lower()

    if extension not in EXTENSIONES_VALIDAS:
        errores.append(f"  ✗ {nombre_archivo} — extensión no soportada ({extension})")
        continue

    try:
        # Verificar que el archivo es una imagen válida
        imagen = Image.open(io.BytesIO(contenido)).convert("RGB")
        ruta_destino = DIRECTORIO_INVENTARIO / nombre_archivo
        imagen.save(ruta_destino, "JPEG", quality=90)
        imagenes_validas.append(ruta_destino)
    except Exception as e:
        errores.append(f"  ✗ {nombre_archivo} — no es una imagen válida: {e}")

# Reporte
print(f"\n{'='*50}")
print(f"Imágenes cargadas exitosamente : {len(imagenes_validas)}")

if errores:
    print(f"Archivos con error             : {len(errores)}")
    for e in errores:
        print(e)

print(f"\nImágenes disponibles:")
for img in sorted(imagenes_validas):
    print(f"  • {img.name}")

"""---
## Sección 4: CLIPService — Wrapper del modelo

Esta clase es el núcleo del sistema. Encapsula toda la lógica de interacción con los modelos CLIP.

**Decisiones de implementación:**
- Se llaman `get_image_features()` y `get_text_features()` directamente, **nunca** `forward()`. El método `forward()` computa pérdidas de entrenamiento que no se necesitan en inferencia.
- La **normalización L2** es obligatoria antes de retornar cualquier vector. Sin ella, el producto punto entre vectores no es equivalente a similitud coseno.
- `torch.no_grad()` desactiva el cálculo del grafo de gradientes. Reduce el uso de memoria a la mitad en inferencia.
- Los dos modelos se cargan una sola vez al instanciar la clase.
"""

# ==============================================================================
# SECCIÓN 4 — CLIPService: wrapper del modelo
# ==============================================================================

import torch
import torch.nn.functional as F
import numpy as np
from PIL import Image
from pathlib import Path
from transformers import CLIPModel, CLIPProcessor
from sentence_transformers import SentenceTransformer
import io


class CLIPService:
    """
    Wrapper de los modelos CLIP para generación de embeddings.

    Modelos:
        - Imagen: openai/clip-vit-base-patch32
        - Texto (español): sentence-transformers/clip-ViT-B-32-multilingual-v1

    Ambos producen vectores de 512 dimensiones en el mismo espacio vectorial,
    lo que permite comparar embeddings de imagen contra embeddings de texto
    usando similitud coseno.
    """

    MODELO_IMAGEN_ID = "openai/clip-vit-base-patch32"
    MODELO_TEXTO_ID  = "sentence-transformers/clip-ViT-B-32-multilingual-v1"
    DIMENSION        = 512

    def __init__(self, device: str = None):
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        print(f"[CLIPService] Iniciando en dispositivo: {self.device}")

        # --- Encoder de imagen ---
        # Se usa CLIPModel completo pero solo se llama get_image_features() en inferencia.
        print(f"[CLIPService] Cargando encoder de imagen ({self.MODELO_IMAGEN_ID})...")
        self._modelo_imagen    = CLIPModel.from_pretrained(self.MODELO_IMAGEN_ID).to(self.device)
        self._procesador_imagen = CLIPProcessor.from_pretrained(self.MODELO_IMAGEN_ID)
        self._modelo_imagen.eval()  # desactiva dropout y batch norm de entrenamiento

        # --- Encoder de texto multilingüe ---
        # SentenceTransformer maneja internamente la tokenización y la normalización.
        # Produce embeddings compatibles con el espacio del modelo de imagen base.
        print(f"[CLIPService] Cargando encoder de texto ({self.MODELO_TEXTO_ID})...")
        self._modelo_texto = SentenceTransformer(self.MODELO_TEXTO_ID, device=self.device)

        print(f"[CLIPService] ✅ Modelos cargados. Dimensión de embeddings: {self.DIMENSION}")

    def encode_image(self, fuente: str | Path | bytes) -> list[float]:
        """
        Genera el embedding de una imagen de forma robusta extrayendo la proyección final.
        """
        imagen = self._cargar_imagen(fuente)

        inputs = self._procesador_imagen(
            images=imagen,
            return_tensors="pt"
        ).to(self.device)

        with torch.no_grad():
            # get_image_features nos devuelve el tensor ya proyectado al espacio de 512
            outputs = self._modelo_imagen.get_image_features(**inputs)

            # Si por alguna razón la versión de transformers devuelve el contenedor BaseModelOutputWithPooling,
            # extraemos el 'pooler_output' o el primer elemento, que es el vector global de la imagen.
            if hasattr(outputs, "pooler_output") and outputs.pooler_output is not None:
                features = outputs.pooler_output
            elif isinstance(outputs, torch.Tensor):
                features = outputs
            else:
                features = outputs[0]

        # Nos aseguramos de tener un shape de [1, 512] antes de normalizar
        if features.dim() > 2:
            # Si viene con secuencia (como el 38400 anterior), tomamos solo el token CLS (índice 0)
            features = features[:, 0, :]

        # Normalización L2 sobre las 512 dimensiones
        features = F.normalize(features, p=2, dim=-1)

        # Retornamos el vector plano de 512 elementos
        return features.view(-1).cpu().tolist()

    QUERY_TEMPLATE = (
        "decoración de eventos: {prompt}. "
        "Estilo visual, colores, materiales y ambiente."
    )

    def encode_text(self, texto: str) -> list[float]:
        """
        Genera el embedding de un texto en español.

        Args:
            texto: prompt del cliente en español.

        Returns:
            Vector normalizado L2 de 512 dimensiones como list[float].

        Raises:
            ValueError: si el texto está vacío.
        """

        texto = texto.strip()
        if not texto:
            raise ValueError("El texto no puede estar vacío.")

        # Enriquecer el prompt aplicando el template de expansión
        texto_expandido = self.QUERY_TEMPLATE.format(prompt=texto)

        # SentenceTransformer ya aplica normalización internamente cuando
        # se especifica normalize_embeddings=True.
        embedding = self._modelo_texto.encode(
            texto_expandido,
            normalize_embeddings=True,
            convert_to_numpy=True
        )


        return embedding.tolist()

    def _cargar_imagen(self, fuente: str | Path | bytes) -> Image.Image:
        """Carga una imagen desde ruta o bytes y la convierte a RGB."""
        try:
            if isinstance(fuente, bytes):
                return Image.open(io.BytesIO(fuente)).convert("RGB")
            return Image.open(fuente).convert("RGB")
        except Exception as e:
            raise ValueError(f"No se pudo cargar la imagen: {e}")


# Instanciar el servicio (se carga una sola vez, se reutiliza en todas las secciones)
clip_service = CLIPService(device=DEVICE)

"""---
## Sección 5: Verificación del CLIPService

Antes de procesar todo el inventario, verificamos que el servicio funciona correctamente con una imagen de prueba.

**Qué se verifica:**
- La imagen se procesa sin errores
- El embedding tiene exactamente 512 dimensiones
- El vector está normalizado (longitud ≈ 1.0)
- El encoder de texto funciona con español
"""

# ==============================================================================
# SECCIÓN 5 — Verificación del CLIPService
# ==============================================================================

import numpy as np

# Usar la primera imagen cargada como imagen de prueba
if not imagenes_validas:
    raise RuntimeError("No hay imágenes cargadas. Ejecuta la Sección 3 primero.")

imagen_prueba = imagenes_validas[0]
print(f"Imagen de prueba: {imagen_prueba.name}")
print("-" * 50)

# --- Test encoder de imagen ---
embedding_imagen = clip_service.encode_image(imagen_prueba)
norma_imagen = np.linalg.norm(embedding_imagen)

print(f"[Encoder imagen]")
print(f"  Dimensiones   : {len(embedding_imagen)} (esperado: 512)")
print(f"  Norma L2      : {norma_imagen:.6f} (esperado: ~1.0)")
print(f"  Primeros 5 valores: {[round(v, 4) for v in embedding_imagen[:5]]}")

assert len(embedding_imagen) == 512, f"Dimensión incorrecta: {len(embedding_imagen)}"
assert abs(norma_imagen - 1.0) < 1e-5, f"Vector no normalizado: norma = {norma_imagen}"
print(f"  ✅ Encoder de imagen OK")

print()

# --- Test encoder de texto ---
texto_prueba = "decoración rústica y elegante para boda campestre"
embedding_texto = clip_service.encode_text(texto_prueba)
norma_texto = np.linalg.norm(embedding_texto)

print(f"[Encoder texto]")
print(f"  Prompt        : '{texto_prueba}'")
print(f"  Dimensiones   : {len(embedding_texto)} (esperado: 512)")
print(f"  Norma L2      : {norma_texto:.6f} (esperado: ~1.0)")
print(f"  Primeros 5 valores: {[round(v, 4) for v in embedding_texto[:5]]}")

assert len(embedding_texto) == 512, f"Dimensión incorrecta: {len(embedding_texto)}"
assert abs(norma_texto - 1.0) < 1e-5, f"Vector no normalizado: norma = {norma_texto}"
print(f"  ✅ Encoder de texto OK")

print()

# --- Test de compatibilidad entre espacios ---
# Los vectores de imagen y texto viven en el mismo espacio de 512 dimensiones.
# Su producto punto es la similitud coseno (ambos están normalizados).
score_cruzado = float(np.dot(embedding_imagen, embedding_texto))
print(f"[Compatibilidad imagen-texto]")
print(f"  Score imagen vs texto de prueba: {score_cruzado:.4f}")
print(f"  (Un valor entre 0.1 y 0.4 es normal para imagen y texto distintos)")
print(f"  ✅ Espacios compatibles")

"""---
## Sección 6: Almacén de embeddings en memoria

En el prototipo de Colab **no conectamos a PostgreSQL**. En cambio, usamos un almacén en memoria que replica exactamente el comportamiento de pgvector.

**Por qué en memoria y no en PostgreSQL aquí:**
- El objetivo de esta fase es validar la calidad de las recomendaciones, no la infraestructura.
- La lógica de búsqueda por similitud coseno es idéntica — solo cambia dónde se almacenan los vectores.
- Conectar a PostgreSQL desde Colab requeriría exponer la BD o tunelizar la conexión, añadiendo complejidad que no aporta a la validación.

La clase `EmbeddingStore` imita exactamente la query pgvector:
```sql
SELECT id, nombre, 1 - (embedding <=> $query) AS score
FROM articulo_inventario
ORDER BY embedding <=> $query
LIMIT $top_k;
```
"""

# ==============================================================================
# SECCIÓN 6 — Almacén de embeddings en memoria (replica pgvector)
# ==============================================================================

import numpy as np
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ArticuloIndexado:
    """Representa un artículo del inventario con su embedding generado."""
    id: str
    nombre: str
    imagen_path: str
    embedding: np.ndarray
    metadata: dict[str, Any] = field(default_factory=dict)


class EmbeddingStore:
    """
    Almacén en memoria de embeddings del inventario.

    Replica el comportamiento del operador <=> de pgvector:
        1 - distancia_coseno(a, b) == producto_punto(a, b)  [vectores normalizados]

    En producción este almacén no existe: los embeddings viven en
    ArticuloInventario.embedding_visual (PostgreSQL vector(512)) y la
    búsqueda la ejecuta pgvector directamente en SQL.
    """

    def __init__(self):
        self._articulos: list[ArticuloIndexado] = []

    def agregar(self, articulo: ArticuloIndexado) -> None:
        """Agrega o reemplaza un artículo en el almacén."""
        # Upsert: si ya existe el ID, reemplaza
        self._articulos = [a for a in self._articulos if a.id != articulo.id]
        self._articulos.append(articulo)

    def buscar(self, query_embedding: list[float], top_k: int = 5, filtro_tipo: str | None = None) -> list[dict]:
        """
        Busca los artículos más similares al query_embedding.

        Equivale a:
            SELECT *, 1 - (embedding <=> $query) AS score
            FROM articulo_inventario
            ORDER BY embedding <=> $query
            LIMIT $top_k;

        Args:
            query_embedding: vector de 512 dimensiones normalizado L2.
            top_k: número de resultados a retornar.

        Returns:
            Lista de dicts con id, nombre, score y metadata, ordenados
            por score descendente (mayor similitud primero).
        """

        # Filtrado previo de los artículos si se especifica el tipo
        articulos_candidatos = self._articulos
        if filtro_tipo:
            articulos_candidatos = [
                a for a in articulos_candidatos
                if a.metadata.get("tipo") == filtro_tipo or a.metadata.get("tipo_articulo") == filtro_tipo
            ]

        if not articulos_candidatos:
            return []

        # Convertir query a numpy array
        query_vec = np.array(query_embedding, dtype=np.float32)

        # Construir matriz solo con los candidatos filtrados
        matriz = np.vstack([a.embedding for a in articulos_candidatos])

        # Multiplicación matricial (Similitud coseno debido a la normalización L2)
        scores = matriz @ query_vec

        # Ordenar índices descendentemente
        indices_ordenados = np.argsort(scores)[::-1][:top_k]

        resultados = []
        for idx in indices_ordenados:
            articulo = articulos_candidatos[idx]
            resultados.append({
                "id": articulo.id,
                "nombre": articulo.nombre,
                "score": float(scores[idx]),
                "metadata": articulo.metadata
            })

        return resultados

    @property
    def total_indexados(self) -> int:
        return len(self._articulos)


# Instancia global del almacén
store = EmbeddingStore()
print("✅ EmbeddingStore inicializado")

"""---
## Sección 7: Seeder — Indexación del inventario

Procesa todas las imágenes subidas, genera sus embeddings y los almacena en el `EmbeddingStore`.

**Este proceso equivale a lo que hará el worker de embeddings en producción** cuando reciba el evento Redis `ia:embedding:pending`.

El ID de cada artículo se toma del nombre del archivo (sin extensión). En producción se usará el `id` real de `ArticuloInventario`.
"""

# ==============================================================================
# SECCIÓN 7 — Seeder: indexación del inventario
# ==============================================================================

import time

if not imagenes_validas:
    raise RuntimeError("No hay imágenes cargadas. Ejecuta la Sección 3 primero.")

print(f"Indexando {len(imagenes_validas)} artículos...")
print("-" * 60)

exitosos = 0
fallidos = []
tiempos = []

for ruta in sorted(imagenes_validas):
    articulo_id = ruta.stem  # nombre del archivo sin extensión
    t_inicio = time.time()

    try:
        embedding = clip_service.encode_image(ruta)
        t_ms = (time.time() - t_inicio) * 1000
        tiempos.append(t_ms)

        store.agregar(ArticuloIndexado(
            id          = articulo_id,
            nombre      = articulo_id.replace("_", " ").replace("-", " ").title(),
            imagen_path = str(ruta),
            embedding   = np.array(embedding),
            metadata    = {"archivo": ruta.name}
        ))

        print(f"  ✅ {articulo_id:<45} {t_ms:6.1f} ms")
        exitosos += 1

    except Exception as e:
        print(f"  ✗ {articulo_id:<45} ERROR: {e}")
        fallidos.append((articulo_id, str(e)))

print("-" * 60)
print(f"Total indexados : {exitosos}")
print(f"Fallidos        : {len(fallidos)}")
if tiempos:
    print(f"Tiempo promedio : {np.mean(tiempos):.1f} ms por artículo")
    print(f"Tiempo total    : {sum(tiempos)/1000:.2f} s")

if fallidos:
    print("\nArticulos con error:")
    for aid, err in fallidos:
        print(f"  - {aid}: {err}")

"""---
## Sección 8: Motor de recomendación

Define las dos funciones principales del sistema:
- `recomendar_por_imagen()`: el cliente sube una foto de referencia
- `recomendar_por_texto()`: el cliente escribe un prompt en español

Ambas funciones siguen exactamente el mismo pipeline:
1. Encodear el input → vector[512] normalizado
2. Buscar los K artículos más cercanos en el espacio de embeddings
3. Retornar los resultados ordenados por score
"""

# ==============================================================================
# SECCIÓN 8 — Motor de recomendación
# ==============================================================================

from IPython.display import display, Image as IPImage
import matplotlib.pyplot as plt
import matplotlib.image as mpimg


def recomendar_por_imagen(
    ruta_imagen: str | Path,
    top_k: int = 5,
    excluir_identica: bool = True
) -> list[dict]:
    """
    Recomienda artículos del inventario similares a la imagen de referencia.

    Args:
        ruta_imagen: ruta a la imagen de referencia del cliente.
        top_k: número de recomendaciones a retornar.
        excluir_identica: si True, excluye artículos con score > 0.9999
                          (evita que el artículo se recomiende a sí mismo
                          cuando la imagen de consulta es del inventario).

    Returns:
        Lista de dicts con id, nombre, score y metadata.
    """
    embedding = clip_service.encode_image(ruta_imagen)
    resultados = store.buscar(embedding, top_k=top_k + (1 if excluir_identica else 0))

    if excluir_identica:
        resultados = [r for r in resultados if r["score"] < 0.9999][:top_k]

    return resultados


def recomendar_por_texto(prompt: str, top_k: int = 5) -> list[dict]:
    """
    Recomienda artículos del inventario que se alineen con el prompt en español.

    Args:
        prompt: descripción del estilo deseado en español.
        top_k: número de recomendaciones a retornar.

    Returns:
        Lista de dicts con id, nombre, score y metadata.
    """
    embedding = clip_service.encode_text(prompt)
    return store.buscar(embedding, top_k=top_k)


def visualizar_resultados(
    resultados: list[dict],
    titulo: str = "Recomendaciones",
    imagen_query: str | Path = None
) -> None:
    """
    Muestra los artículos recomendados con sus imágenes y scores de forma robusta usando PIL.
    """
    n_cols = len(resultados) + (1 if imagen_query else 0)
    fig, axes = plt.subplots(1, n_cols, figsize=(4 * n_cols, 5))

    if n_cols == 1:
        axes = [axes]

    col = 0

    # Mostrar imagen de consulta si se provee (Carga segura con PIL)
    if imagen_query:
        try:
            # PIL detecta el formato real automáticamente, ignorando si la extensión miente
            img = Image.open(str(imagen_query)).convert("RGB")
            axes[col].imshow(img)
        except Exception as e:
            axes[col].text(0.5, 0.5, f"Error consulta\n{e}", ha="center", va="center", color="red")

        axes[col].set_title("CONSULTA", fontsize=10, fontweight="bold", color="blue")
        axes[col].axis("off")
        col += 1

    # Mostrar artículos recomendados
    for i, resultado in enumerate(resultados):
        ruta_img = DIRECTORIO_INVENTARIO / resultado["metadata"].get("archivo", "")

        if ruta_img.exists():
            try:
                img = Image.open(str(ruta_img)).convert("RGB")
                axes[col].imshow(img)
            except Exception:
                axes[col].text(0.5, 0.5, "Error de formato", ha="center", va="center")
        else:
            axes[col].text(0.5, 0.5, "Sin imagen", ha="center", va="center")

        nombre_corto = resultado["nombre"][:25]
        axes[col].set_title(
            f"#{i+1} {nombre_corto}\nScore: {resultado['score']:.3f}",
            fontsize=8
        )
        axes[col].axis("off")
        col += 1

    fig.suptitle(titulo, fontsize=12, fontweight="bold")
    plt.tight_layout()
    plt.show()

print("✅ Motor de recomendación listo")
print(f"   Artículos indexados: {store.total_indexados}")

"""---
## Sección 9: Casos de prueba — Validación cualitativa

Ejecuta los casos de prueba del plan de implementación.

### Test de sanidad (T-06): imagen del inventario vs sí misma

**Este es el test más importante.** Si un artículo buscado por su propia imagen no aparece con score > 0.95, hay un error en el pipeline.
"""

# ==============================================================================
# SECCIÓN 9A — T-06: Test de sanidad del pipeline
# ==============================================================================
# Buscamos cada artículo del inventario usando su propia imagen como query.
# El artículo debe aparecer en posición #1 con score > 0.95.
# Si esto falla, hay un error en el pipeline antes de validar la calidad.
# ==============================================================================

print("T-06: Test de sanidad — imagen del inventario vs sí misma")
print("=" * 60)

aprobados = 0
fallidos_t06 = []

for ruta in sorted(imagenes_validas):
    articulo_id = ruta.stem
    embedding = clip_service.encode_image(ruta)

    # Buscar sin excluir idénticos para este test
    resultados = store.buscar(embedding, top_k=1)

    if not resultados:
        fallidos_t06.append((articulo_id, "sin resultados"))
        continue

    primer_resultado = resultados[0]
    score = primer_resultado["score"]
    es_correcto = primer_resultado["id"] == articulo_id
    score_ok = score > 0.95

    if es_correcto and score_ok:
        print(f"  ✅ {articulo_id:<40} score: {score:.4f}")
        aprobados += 1
    else:
        motivo = []
        if not es_correcto:
            motivo.append(f"retornó '{primer_resultado['id']}' en lugar de sí mismo")
        if not score_ok:
            motivo.append(f"score {score:.4f} < 0.95")
        print(f"  ✗ {articulo_id:<40} {', '.join(motivo)}")
        fallidos_t06.append((articulo_id, ", ".join(motivo)))

print("-" * 60)
print(f"Aprobados: {aprobados}/{len(imagenes_validas)}")

if fallidos_t06:
    print("\n⚠️  Artículos con problemas:")
    for aid, motivo in fallidos_t06:
        print(f"   - {aid}: {motivo}")
    print("\n   Posibles causas:")
    print("   1. Fondos ruidosos o con mucho contexto en las imágenes")
    print("   2. Dos artículos con imágenes muy similares")
    print("   3. Error en la carga o procesamiento de alguna imagen")
else:
    print("\n✅ T-06 aprobado — el pipeline funciona correctamente")

# ==============================================================================
# SECCIÓN 9B — Recomendación por imagen de referencia externa
# ==============================================================================
# Sube una imagen de referencia del cliente (foto de Pinterest, inspiración, etc.)
# y verifica que el sistema recomienda artículos visualmente coherentes.
# ==============================================================================

print("Sube una imagen de referencia del cliente (foto de inspiración):")
archivo_referencia = files.upload()

if not archivo_referencia:
    print("No se subió ningún archivo.")
else:
    nombre_ref, contenido_ref = next(iter(archivo_referencia.items()))
    ruta_referencia = Path("/content") / nombre_ref

    # Guardar imagen de referencia
    imagen_ref = Image.open(io.BytesIO(contenido_ref)).convert("RGB")
    imagen_ref.save(ruta_referencia, "JPEG", quality=90)

    print(f"\nBuscando artículos similares a: {nombre_ref}")
    print("-" * 50)

    resultados = recomendar_por_imagen(ruta_referencia, top_k=5)

    # Mostrar resultados en texto
    for i, r in enumerate(resultados):
        print(f"  #{i+1}  {r['nombre']:<40}  score: {r['score']:.4f}")

    # Visualizar con imágenes
    visualizar_resultados(
        resultados,
        titulo=f"Recomendaciones para: {nombre_ref}",
        imagen_query=ruta_referencia
    )

# ==============================================================================
# SECCIÓN 9C — Recomendación por texto en español
# ==============================================================================
# Modifica la variable PROMPT con el texto que quieras probar.
# El modelo multilingüe entiende español de forma nativa.
# ==============================================================================

# ── MODIFICA ESTE PROMPT PARA TUS PRUEBAS ─────────────────────────────────────
PROMPT = "decoración elegante y romántica para boda, colores dorados y blancos"
TOP_K  = 5
# ──────────────────────────────────────────────────────────────────────────────

print(f"Prompt: '{PROMPT}'")
print("-" * 60)

resultados = recomendar_por_texto(PROMPT, top_k=TOP_K)

for i, r in enumerate(resultados):
    print(f"  #{i+1}  {r['nombre']:<40}  score: {r['score']:.4f}")

visualizar_resultados(
    resultados,
    titulo=f"Prompt: '{PROMPT}'"
)

# ==============================================================================
# SECCIÓN 9D — Playground: prueba libre de prompts
# ==============================================================================
# Celda para iterar rápido sobre distintos prompts durante la validación.
# Modifica PROMPTS_PRUEBA con los casos relevantes para tu inventario.
# ==============================================================================

PROMPTS_PRUEBA = [
    "ambiente rústico y natural para boda campestre",
    "decoración moderna y minimalista en blanco",
    "estilo glamour con dorados y brillantes",
    "ambiente romántico con flores y encajes",
    "decoración bohemia con elementos naturales",
]

TOP_K_PLAYGROUND = 3

print(f"{'PROMPT':<55} {'#1':<30} {'Score':>6}  {'#2':<30} {'Score':>6}")
print("=" * 140)

for prompt in PROMPTS_PRUEBA:
    resultados = recomendar_por_texto(prompt, top_k=TOP_K_PLAYGROUND)

    nombre_1 = resultados[0]["nombre"][:28] if len(resultados) > 0 else "—"
    score_1  = resultados[0]["score"]       if len(resultados) > 0 else 0
    nombre_2 = resultados[1]["nombre"][:28] if len(resultados) > 1 else "—"
    score_2  = resultados[1]["score"]       if len(resultados) > 1 else 0

    prompt_corto = prompt[:53]
    print(f"{prompt_corto:<55} {nombre_1:<30} {score_1:>6.3f}  {nombre_2:<30} {score_2:>6.3f}")

"""---
## Sección 10: Análisis de similitud entre artículos

Genera la **matriz de similitud** entre todos los artículos del inventario. Útil para:
- Detectar artículos con imágenes demasiado similares entre sí (posibles duplicados visuales)
- Entender qué grupos de artículos el modelo percibe como visualmente relacionados
- Identificar artículos con embeddings muy distintos al resto (posibles problemas de imagen)
"""

# ==============================================================================
# SECCIÓN 10 — Matriz de similitud entre artículos
# ==============================================================================

import matplotlib.pyplot as plt
import numpy as np

# Reconstruir lista de artículos desde el store
articulos = store._articulos
n = len(articulos)

if n < 2:
    print("Se necesitan al menos 2 artículos para generar la matriz.")
else:
    # Matriz de embeddings: shape (N, 512)
    matriz = np.stack([a.embedding for a in articulos])

    # Similitud coseno entre todos los pares: shape (N, N)
    # Los vectores ya están normalizados L2, por lo que producto punto == coseno
    similitud = matriz @ matriz.T

    # Nombres cortos para los ejes
    nombres = [a.nombre[:20] for a in articulos]

    fig, ax = plt.subplots(figsize=(max(8, n * 0.7), max(6, n * 0.6)))

    im = ax.imshow(similitud, cmap="RdYlGn", vmin=0, vmax=1, aspect="auto")
    plt.colorbar(im, ax=ax, label="Similitud coseno")

    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    ax.set_xticklabels(nombres, rotation=45, ha="right", fontsize=7)
    ax.set_yticklabels(nombres, fontsize=7)

    # Anotar scores en cada celda si el inventario es pequeño
    if n <= 15:
        for i in range(n):
            for j in range(n):
                ax.text(j, i, f"{similitud[i,j]:.2f}",
                        ha="center", va="center", fontsize=6,
                        color="black" if similitud[i,j] < 0.7 else "white")

    ax.set_title("Matriz de similitud coseno entre artículos del inventario", pad=15)
    plt.tight_layout()
    plt.show()

    # Detectar pares con alta similitud (posibles duplicados visuales)
    print("\nPares de artículos con similitud > 0.85 (excluye diagonal):")
    encontrados = False
    for i in range(n):
        for j in range(i + 1, n):
            if similitud[i, j] > 0.85:
                print(f"  {articulos[i].nombre[:30]:<32} ↔  {articulos[j].nombre[:30]:<32}  score: {similitud[i,j]:.3f}")
                encontrados = True

    if not encontrados:
        print("  Ninguno — buena diversidad visual en el inventario")

"""---
## Sección 11: Reporte final de validación

Genera un resumen del estado de la validación para determinar si el prototipo está listo para pasar a la implementación del servicio de producción.

**Criterio de aprobación (del plan de implementación):** mínimo 4 de 6 casos de prueba aprobados. Si T-06 falla, la fase no se aprueba independientemente del resto.
"""

# ==============================================================================
# SECCIÓN 11 — Reporte final de validación
# ==============================================================================
# Completa manualmente el resultado de cada caso de prueba después de
# ejecutar las secciones 9A-9D y evaluar cualitativamente los resultados.
# ==============================================================================

# ── COMPLETAR MANUALMENTE DESPUÉS DE EVALUAR CADA CASO ────────────────────────
resultados_casos = {
    "T-01": {"descripcion": "Imagen boda bohemia → artículos rústicos/naturales",   "aprobado": None},
    "T-02": {"descripcion": "Imagen evento corporativo → artículos formales",        "aprobado": None},
    "T-03": {"descripcion": "Imagen quinceañera → artículos románticos/dorados",     "aprobado": None},
    "T-04": {"descripcion": "Texto: rústico pero elegante",                           "aprobado": None},
    "T-05": {"descripcion": "Texto: decoración minimalista en blanco",                "aprobado": None},
    "T-06": {"descripcion": "Imagen del inventario → score > 0.95 en posición #1",
             "aprobado": len(fallidos_t06) == 0 if 'fallidos_t06' in dir() else None},
}
# Ejemplo: cambia None por True o False según tus observaciones
# "T-01": {"aprobado": True},
# ──────────────────────────────────────────────────────────────────────────────

print("REPORTE DE VALIDACIÓN — FASE 1")
print("=" * 65)
print(f"{'CASO':<8} {'DESCRIPCIÓN':<48} {'ESTADO':>8}")
print("-" * 65)

aprobados_total = 0
evaluados = 0
t06_aprobado = None

for caso, datos in resultados_casos.items():
    estado = datos["aprobado"]
    if estado is True:
        simbolo = "✅ PASA"
        aprobados_total += 1
        evaluados += 1
    elif estado is False:
        simbolo = "✗ FALLA"
        evaluados += 1
    else:
        simbolo = "— PENDIENTE"

    if caso == "T-06":
        t06_aprobado = estado

    print(f"  {caso:<6} {datos['descripcion']:<48} {simbolo:>10}")

print("-" * 65)

if evaluados > 0:
    print(f"\nCasos aprobados: {aprobados_total}/{evaluados}")

    if t06_aprobado is False:
        print("\n❌ FASE 1 NO APROBADA — T-06 falló.")
        print("   Revisar la calidad de las imágenes del inventario.")
    elif aprobados_total >= 4:
        print("\n✅ FASE 1 APROBADA — listo para implementar el servicio de producción.")
    else:
        print(f"\n⚠️  FASE 1 PENDIENTE — se requieren al menos 4 aprobados ({aprobados_total} actuales).")
        print("   Revisar calidad de imágenes o ajustar prompts de prueba.")
else:
    print("\n⏳ Completa los casos de prueba en las secciones 9A-9D y")
    print("   actualiza el diccionario 'resultados_casos' arriba.")