spring.application.name=decoraciones

spring.profiles.active=dev
server.port=8080
server.servlet.context-path=/api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.filter=true

spring.datasource.url=jdbc:postgresql://localhost:5433/decoraciones
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.init_commands=CREATE EXTENSION IF NOT EXISTS vector;
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.issuer=decoraciones
app.jwt.access-token-ttl=PT15M
app.jwt.refresh-token-ttl=P7D
app.jwt.private-key=classpath:certs/private.pem
app.jwt.public-key=classpath:certs/public.pem

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

resend.api-key=${RESEND_API_KEY:re_123456789}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}

app.base-url=http://localhost:8080/api
app.upload.dir=${APP_UPLOAD_DIR}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

app.reserva.lock-ttl-minutes=15

app.ia.url=http://localhost:8003


# PAGOFACIL
pagofacil.base-url=${PAGOFACIL_BASE_URL:https://masterqr.pagofacil.com.bo/api/services/v2}
pagofacil.token-service=${PAGOFACIL_TOKEN_SERVICE:a52063a1be51238364d1e55c3132f7c3b0625cfab2f37ac522a85cabaebdeb993bc8f601284fc35eee7f983e663d375c58f835b94a2aa558e8e2f9693885a2156598e1da9a7bf8caba2f3d6459f167fed3a50a375e0d80d517b560f04f017db078c3ee80e37f608537e752c82629095fbdcc6a4edcf4f22269c2f98f5d431c72}
pagofacil.token-secret=${PAGOFACIL_TOKEN_SECRET:eed967baf4b64e8980051c1b}
pagofacil.callback-url=${PAGOFACIL_CALLBACK_URL:https://tu-dominio.com/callback}
pagofacil.test-mode.enabled=${PAGOFACIL_TEST_MODE_ENABLED:true}
pagofacil.test-mode.monto-simulado=${PAGOFACIL_TEST_MODE_MONTO_SIMULADO:0.10}


